version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30000:80"
    container_name: bull_chat
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

