version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30000:80"
    container_name: bull_chat
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_CORS_ORIGIN=http://localhost:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=bull-chat;Username=postgres;Password=1234
    depends_on:
      - db
      - migrate

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    working_dir: /backend
    command: dotnet ef database update --verbose
    container_name: bull_chat_migrate
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=bull-chat;Username=postgres;Password=1234

  db:
    image: postgres:latest
    container_name: postgres_bull_chat
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bull-chat
    volumes:
      - ./bull-chat-data:/var/lib/postgresql/data

volumes:
  postgres_data:
