version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_bull_chat
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bull-chat
    volumes:
      - ./bull-chat-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    working_dir: /backend
    command: /root/.dotnet/tools/dotnet-ef database update
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=bull-chat;Username=postgres;Password=1234
    depends_on:
      db:
        condition: service_healthy
