services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    working_dir: /backend
    command: dotnet ef database update --verbose
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=bull-chat;Username=postgres;Password=1234
    depends_on:
      db:
        condition: service_healthy
